In [5]:
import pymongo
import pandas as pd
from pymongo import MongoClient

client = MongoClient()

db = client.movie_database

collection = db.movies

df = pd.DataFrame(list(collection.find()))

df.head()

,_id,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,...,Type,DVD,BoxOffice,Production,Website,Response,totalSeasons,Season,Episode,seriesID
0,666a8cf1fb459925bc9230d8,Carmencita,1894,Not Rated,10 Mar 1894,1 min,"Documentary, Short",William K.L. Dickson,N/A,Carmencita,...,movie,N/A,N/A,N/A,N/A,True,NaN,NaN,NaN,NaN
1,666a8cf1fb459925bc9230d9,Le clown et ses chiens,1892,N/A,16 Nov 1892,5 min,"Animation, Short",Émile Reynaud,N/A,N/A,...,movie,N/A,N/A,N/A,N/A,True,NaN,NaN,NaN,NaN
2,666a8cf1fb459925bc9230da,Pauvre Pierrot,1892,TV-PG,28 Oct 1892,4 min,"Animation, Comedy, Short",Émile Reynaud,N/A,N/A,...,movie,N/A,N/A,N/A,N/A,True,NaN,NaN,NaN,NaN
3,666a8cf1fb459925bc9230db,Un bon bock,1892,N/A,28 Oct 1892,12 min,"Animation, Short",Émile Reynaud,N/A,N/A,...,movie,N/A,N/A,N/A,N/A,True,NaN,NaN,NaN,NaN
4,666a8cf1fb459925bc9230dc,Blacksmith Scene,1893,Unrated,09 May 1893,1 min,"Short, Comedy",William K.L. Dickson,N/A,"Charles Kayser, John Ott",...,movie,N/A,N/A,N/A,N/A,True,NaN,NaN,NaN,NaN

In [6]:
df['imdbRating'].replace('N/A', 0, inplace=True)
df['imdbVotes'].replace('N/A', 0, inplace=True)

df['imdbRating'].replace('NaN', 0, inplace=True)
df['imdbVotes'].replace('NaN', 0, inplace=True)

df.drop(['_id', 'DVD','Rated', 'BoxOffice', 'Production', 'Website', 'Response', 'Released', 'Runtime', 'Ratings', 'Metascore', 'Type', 'totalSeasons', 'Season', 'Episode', 'seriesID', 'Country', 'Awards'], axis=1, inplace=True)


df.head()

C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3439657239.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbRating'].replace('N/A', 0, inplace=True)
C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3439657239.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbVotes'].replace('N/A', 0, inplace=True)
C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3439657239.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbRating'].replace('NaN', 0, inplace=True)
C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3439657239.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbVotes'].replace('NaN', 0, inplace=True)

,Title,Year,Genre,Director,Writer,Actors,Plot,Language,Poster,imdbRating,imdbVotes,imdbID
0,Carmencita,1894,"Documentary, Short",William K.L. Dickson,N/A,Carmencita,"Presumably, the first woman ever to appear in ...",None,https://m.media-amazon.com/images/M/MV5BZmUzOW...,5.7,"2,014",tt0000001
1,Le clown et ses chiens,1892,"Animation, Short",Émile Reynaud,N/A,N/A,Lost short film consisting of 300 painted imag...,None,https://m.media-amazon.com/images/M/MV5BZDI4ZD...,6.0,270,tt0000002
2,Pauvre Pierrot,1892,"Animation, Comedy, Short",Émile Reynaud,N/A,N/A,"One night, Arlequin come to see his lover Colo...",None,https://m.media-amazon.com/images/M/MV5BYWZiY2...,6.5,"1,934",tt0000003
3,Un bon bock,1892,"Animation, Short",Émile Reynaud,N/A,N/A,A wanderer comes into a cabaret in the country...,None,https://m.media-amazon.com/images/M/MV5BOGI5Nj...,6.1,178,tt0000004
4,Blacksmith Scene,1893,"Short, Comedy",William K.L. Dickson,N/A,"Charles Kayser, John Ott",A stationary camera looks at a large anvil wit...,None,https://m.media-amazon.com/images/M/MV5BNDg0ZD...,6.2,"2,685",tt0000005

In [8]:
import pymongo
import pandas as pd
from pymongo import MongoClient

client = MongoClient()

db = client.movie_database

collection = db.movies

df = pd.DataFrame(list(collection.find()))

df['imdbRating'].replace('N/A', 0, inplace=True)
df['imdbVotes'].replace('N/A', 0, inplace=True)

df['imdbRating'].replace('NaN', 0, inplace=True)
df['imdbVotes'].replace('NaN', 0, inplace=True)



df.head()



# Function to recommend top 10 movies for each genre and preferred languages
def recommend_movies_by_genre_and_language(genre, languages):
    # Filter dataframe for the given genre and preferred languages
    genre_df = df[df['Genre'].str.contains(genre) & df['Language'].apply(lambda x: any(lang in x for lang in languages))]

    # Sort by imdbVotes and imdbRating in descending order
    sorted_df = genre_df.sort_values(by=['imdbVotes', 'imdbRating'], ascending=False)

    # Select top 10 movies
    top_movies = sorted_df.head(10)
    
    return top_movies


recommendations = {}

for genre in ['Action', 'Comedy', 'Thriller']:
    recommendations[genre] = recommend_movies_by_genre_and_language(genre, ['English'])

# Print recommendations
for genre, movies in recommendations.items():
    print(f"\nTop 10 Movies in {genre} for Preferred Languages:\n")
    print(movies)

C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3713371377.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbRating'].replace('N/A', 0, inplace=True)
C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3713371377.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbVotes'].replace('N/A', 0, inplace=True)
C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3713371377.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbRating'].replace('NaN', 0, inplace=True)
C:\Users\lalan\AppData\Local\Temp\ipykernel_18276\3713371377.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdbVotes'].replace('NaN', 0, inplace=True)

Top 10 Movies in Action for Preferred Languages:

                             _id                                       Title  \
123590  666a92b94bf9c7aca214b21f                                   Astro Boy
34488   666a8d81fb459925bc92b790                    Superman: The Bulleteers
66774   666a8e01fb459925bc9335ae                              Captain Apache
247984  666c20bcc28a07fdd11613e6                            WrestleMania XII
108968  666a92764bf9c7aca2147901                               Blind Justice
268049  666c2121c28a07fdd1166247  Super Mario RPG: Legend of the Seven Stars
34946   666a8d83fb459925bc92b95a            Superman: The Magnetic Telescope
74310   666a8e20fb459925bc93531e                                 Eat My Dust
438485  666c253cc28a07fdd118fc0b                                  Blue Demon
36331   666a8d87fb459925bc92bec3                                Super-Rabbit

             Year      Rated     Released  Runtime  \
123590  1980–2004       TV-G  07 Jul 1987   24 min
34488        1942  Not Rated  26 Mar 1942    8 min
66774        1971         GP  27 Oct 1971   94 min
247984       1996      TV-14  31 Mar 1996  168 min
108968       1994          R  25 Jun 1994   85 min
268049       1996        K-A  13 May 1996      N/A
34946        1942   Approved  24 Apr 1942    8 min
74310        1976         PG  21 Oct 1976   89 min
438485       2004      PG-13  15 Oct 2004   95 min
36331        1943   Approved  03 Apr 1943    8 min

                                                    Genre  \
123590                       Animation, Action, Adventure
34488                            Animation, Short, Action
66774                                Action, Crime, Drama
247984                                      Action, Sport
108968                             Action, Drama, Western
268049                         Action, Adventure, Fantasy
34946                            Animation, Short, Action
74310                             Action, Comedy, Romance
438485  Action, Adventure, Comedy, Horror, Sci-Fi, Thr...
36331                            Animation, Short, Action

                                  Director  \
123590                                 N/A
34488      Dave Fleischer, Orestes Calpini
66774                     Alexander Singer
247984                          Kevin Dunn
108968                      Richard Spence
268049  Chihiro Fujioka, Yoshihiko Maekawa
34946         Dave Fleischer, Thomas Moore
74310                  Charles B. Griffith
438485                      Daniel Grodnik
36331                          Chuck Jones

                                                   Writer  \
123590                                                N/A
34488              Joe Shuster, Jerry Siegel, Bill Turner
66774        Philip Yordan, Milton Sperling, S.E. Whitman
247984                                         Joe Bustos
108968                                       Daniel Knauf
268049                      Shigeru Miyamoto (characters)
34946               Jerry Siegel, Joe Shuster, Dan Gordon
74310                                 Charles B. Griffith
438485  Brett Thompson, Lisa Morton, Ron Oliver, Danie...
36331                                         Tedd Pierce

                                                   Actors  ...    Type  \
123590   Richard Ganoung, Gregory North, Nicholas Podbrey  ...  series
34488           Bud Collyer, Joan Alexander, Jackson Beck  ...   movie
66774        Lee Van Cleef, Carroll Baker, Stuart Whitman  ...   movie
247984            Bret Hart, Shawn Michaels, Mark Calaway  ...   movie
108968        Armand Assante, Elisabeth Shue, Robert Davi  ...   movie
268049                                                N/A  ...    game
34946           Bud Collyer, Joan Alexander, Jackson Beck  ...   movie
74310          Ron Howard, Christopher Norris, Brad David  ...   movie
438485  Dedee Pfeiffer, Randall Batinkoff, Danny Woodb...  ...   movie
36331                 Mel Blanc, Tedd Pierce, Kent Rogers  ...   movie

                DVD BoxOffice Production Website Response totalSeasons Season  \
123590          NaN       NaN        NaN     NaN     True            2    NaN
34488           N/A       N/A        N/A     N/A     True          NaN    NaN
66774   26 Jul 2020       N/A        N/A     N/A     True          NaN    NaN
247984          N/A       N/A        N/A     N/A     True          NaN    NaN
108968          N/A       N/A        N/A     N/A     True          NaN    NaN
268049          N/A       N/A        N/A     N/A     True          NaN    NaN
34946           N/A       N/A        N/A     N/A     True          NaN    NaN
74310   18 Jun 2018       N/A        N/A     N/A     True          NaN    NaN
438485  22 May 2017       N/A        N/A     N/A     True          NaN    NaN
36331           N/A       N/A        N/A     N/A     True          NaN    NaN

       Episode seriesID
123590     NaN      NaN
34488      NaN      NaN
66774      NaN      NaN
247984     NaN      NaN
108968     NaN      NaN
268049     NaN      NaN
34946      NaN      NaN
74310      NaN      NaN
438485     NaN      NaN
36331      NaN      NaN

[10 rows x 30 columns]

Top 10 Movies in Comedy for Preferred Languages:

                             _id                    Title       Year  \
173374  666a93964bf9c7aca2157497                 The Trap       1991
18269   666a8d3cfb459925bc927835  Putting Pants on Philip       1927
79542   666a8e36fb459925bc93678e         A Perfect Couple       1979
87321   666a92174bf9c7aca2142472     Just the Way You Are       1984
71084   666a8e14fb459925bc934684   The Best of Benny Hill       1974
35705   666a8d84fb459925bc92bc51     Daffy - The Commando       1943
239542  666a96e6c572530af29ed373            South Pacific       2001
103459  666a925e4bf9c7aca214637c             Bad Channels       1992
96287   666a923f4bf9c7aca2144778    The Arsenio Hall Show  1989–1994
57175   666a8ddbfb459925bc93102f       Mad as a Mars Hare       1963

            Rated     Released  Runtime                          Genre  \
173374  Not Rated  15 Jun 1991   27 min          Comedy, Crime, Horror
18269      Passed  03 Dec 1927   20 min                  Comedy, Short
79542          PG  05 Jan 1981  110 min       Comedy, Musical, Romance
87321          PG  16 Nov 1984   94 min         Comedy, Music, Romance
71084   Not Rated  23 May 1974   83 min                         Comedy
35705    Approved  20 Nov 1943    7 min       Animation, Short, Comedy
239542        N/A  26 Mar 2001  135 min         Comedy, Drama, Musical
103459          R  11 May 1994   88 min  Comedy, Horror, Music, Sci-Fi
96287         N/A  03 Jan 1989   60 min       Comedy, Music, Talk-Show
57175    Approved  19 Oct 1963    7 min       Animation, Short, Comedy

                          Director  \
173374              Michael J. Fox
18269               Clyde Bruckman
79542                Robert Altman
87321             Édouard Molinaro
71084                  John Robins
35705                 Friz Freleng
239542              Richard Pearce
103459                Ted Nicolaou
96287                          N/A
57175   Chuck Jones, Maurice Noble

                                                   Writer  \
173374                       Scott Alexander, Steven Dodd
18269                            Leo McCarey, H.M. Walker
79542                    Robert Altman, Allan F. Nicholls
87321                                         Allan Burns
71084                                          Benny Hill
35705                                     Michael Maltese
239542  James A. Michener, Oscar Hammerstein II, Joshu...
103459  Charles Band (original idea), Jackson Barr (sc...
96287                                                 N/A
57175                                        John W. Dunn

                                                   Actors  ...     Type  \
173374               Teri Garr, Bruno Kirby, Bruce McGill  ...  episode
18269       Stan Laurel, Oliver Hardy, Chester A. Bachman  ...    movie
79542             Paul Dooley, Marta Heflin, Titos Vandis  ...    movie
87321       Kristy McNichol, Michael Ontkean, Kaki Hunter  ...    movie
71084              Benny Hill, Patricia Hayes, Eira Heath  ...    movie
35705                                           Mel Blanc  ...    movie
239542    Glenn Close, Harry Connick Jr., Rade Serbedzija  ...    movie
103459  Robert Factor, Martha Quinn, Aaron Lustig, Mic...  ...    movie
96287      Arsenio Hall, Burton Richardson, Michael Wolff  ...   series
57175                                           Mel Blanc  ...    movie

                DVD   BoxOffice Production Website Response totalSeasons  \
173374          NaN         NaN        NaN     NaN     True          NaN
18269           N/A         N/A        N/A     N/A     True          NaN
79542   22 May 2017         N/A        N/A     N/A     True          NaN
87321   22 Aug 2018  $7,889,694        N/A     N/A     True          NaN
71084           N/A         N/A        N/A     N/A     True          NaN
35705           N/A         N/A        N/A     N/A     True          NaN
239542          N/A         N/A        N/A     N/A     True          NaN
103459  23 Mar 2017         N/A        N/A     N/A     True          NaN
96287           NaN         NaN        NaN     NaN     True            6
57175           N/A         N/A        N/A     N/A     True          NaN

       Season Episode   seriesID
173374      3       3  tt0096708
18269     NaN     NaN        NaN
79542     NaN     NaN        NaN
87321     NaN     NaN        NaN
71084     NaN     NaN        NaN
35705     NaN     NaN        NaN
239542    NaN     NaN        NaN
103459    NaN     NaN        NaN
96287     NaN     NaN        NaN
57175     NaN     NaN        NaN

[10 rows x 30 columns]

Top 10 Movies in Thriller for Preferred Languages:

                             _id                                      Title  \
73450   666a8e1efb459925bc934fc2                             Psychic Killer
112485  666a92874bf9c7aca21486be  Deadly Invasion: The Killer Bee Nightmare
109798  666a927b4bf9c7aca2147c3f                      The Cold Light of Day
62372   666a8deffb459925bc93247c                               Warning Shot
65750   666a8dfdfb459925bc9331ae                      How Awful About Allan
41553   666a8d9dfb459925bc92d329                The Man on the Eiffel Tower
206720  666a941f4bf9c7aca215f6d9                      The Turn of the Screw
424178  666c2503c28a07fdd118c428                                   Sandwich
438485  666c253cc28a07fdd118fc0b                                 Blue Demon
92197   666a922a4bf9c7aca214377e                              A Perfect Spy

        Year      Rated     Released  Runtime  \
73450   1975         PG  01 Dec 1975   89 min
112485  1995      TV-14  28 Feb 1995   85 min
109798  1996        N/A  18 Jan 1996  101 min
62372   1966  Not Rated  18 Jan 1967  100 min
65750   1970         PG  22 Sep 1970   73 min
41553   1949    Unrated  04 Feb 1950   97 min
206720  1999  Not Rated  27 Feb 2000  100 min
424178  2006  Not Rated  25 Aug 2006  152 min
438485  2004      PG-13  15 Oct 2004   95 min
92197   1987        N/A  04 Nov 1987  374 min

                                                    Genre  \
73450                                    Horror, Thriller
112485                           Horror, Sci-Fi, Thriller
109798                                    Drama, Thriller
62372                            Crime, Mystery, Thriller
65750                                    Horror, Thriller
41553                                   Mystery, Thriller
206720                            Drama, Horror, Thriller
424178                                   Comedy, Thriller
438485  Action, Adventure, Comedy, Horror, Sci-Fi, Thr...
92197                                            Thriller

                                                Director  \
73450                                         Ray Danton
112485                                Rockne S. O'Bannon
109798                               Rudolf van den Berg
62372                                         Buzz Kulik
65750                                  Curtis Harrington
41553   Burgess Meredith, Irving Allen, Charles Laughton
206720                                          Ben Bolt
424178                                      Anees Bazmee
438485                                    Daniel Grodnik
92197                                                N/A

                                                   Writer  \
73450              Greydon Clark, Mikel Angel, Ray Danton
112485       William Bast, Paul Huson, Rockne S. O'Bannon
109798                   Friedrich Dürrenmatt, Doug Magee
62372                          Whit Masterson, Mann Rubin
65750                                       Henry Farrell
41553                        Harry Brown, Georges Simenon
206720                             Nick Dear, Henry James
424178                                       Anees Bazmee
438485  Brett Thompson, Lisa Morton, Ron Oliver, Danie...
92197                                                 N/A

                                                   Actors  ...    Type  \
73450                 Paul Burke, Jim Hutton, Julie Adams  ...   movie
112485        Robert Hays, Nancy Stafford, Ryan Phillippe  ...   movie
109798     Richard E. Grant, Lynsey Baxter, Perdita Weeks  ...   movie
62372               David Janssen, Ed Begley, Keenan Wynn  ...   movie
65750         Anthony Perkins, Julie Harris, Joan Hackett  ...   movie
41553   Charles Laughton, Franchot Tone, Burgess Meredith  ...   movie
206720              Caroline Pegg, Jodhi May, Colin Firth  ...   movie
424178           Govinda, Raveena Tandon, Mahima Chaudhry  ...   movie
438485  Dedee Pfeiffer, Randall Batinkoff, Danny Woodb...  ...   movie
92197          Ray McAnally, Rüdiger Weigang, Alan Howard  ...  series

                DVD BoxOffice             Production Website Response  \
73450   02 Dec 1991       N/A  AVCO Embassy Pictures     N/A     True
112485          N/A       N/A                    N/A     N/A     True
109798  22 May 2017       N/A                    N/A     N/A     True
62372   15 May 2016       N/A                    N/A     N/A     True
65750   30 Aug 2016       N/A                    N/A     N/A     True
41553   17 Apr 2020       N/A                    N/A     N/A     True
206720          N/A       N/A                    N/A     N/A     True
424178  28 Feb 2017       N/A                    N/A     N/A     True
438485  22 May 2017       N/A                    N/A     N/A     True
92197           NaN       NaN                    NaN     NaN     True

       totalSeasons Season Episode seriesID
73450           NaN    NaN     NaN      NaN
112485          NaN    NaN     NaN      NaN
109798          NaN    NaN     NaN      NaN
62372           NaN    NaN     NaN      NaN
65750           NaN    NaN     NaN      NaN
41553           NaN    NaN     NaN      NaN
206720          NaN    NaN     NaN      NaN
424178          NaN    NaN     NaN      NaN
438485          NaN    NaN     NaN      NaN
92197             1    NaN     NaN      NaN

[10 rows x 30 columns]